# Generated by Django 4.2 on 2023-04-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Token",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("unique_hash", models.CharField(max_length=255, unique=True)),
                ("tx_hash", models.CharField(max_length=255)),
                ("media_url", models.URLField()),
                ("owner", models.CharField(max_length=42)),
            ],
        ),
    ]
